### ISSUE TITLE
Might I suggest making a release for 1.1?

### ISSUE THREAD

**Issue by Webatron11** [thatfellarobin/axon#6]

**Comment by thatfellarobin** [comment]
I'm still working on it. I plan to do so once it gets to that point.

**Comment by Webatron11** [comment]
Oh nice, i just got confused cause the end of the readme mentioned 1.1. Any tips for putting one of these together? In interested in it for a travel board

**Comment by thatfellarobin** [comment]
Depends. I can't say confidently at this point that I recommend either the 1.0 or development 1.1 versions. 1.0 evidently worked for me, but some parts of it are a little suspect if you order from cheaper fabs.

I'm interested in eventually selling some kits. However, I'm busy with real life stuff and it takes time and money to develop and test more prototypes so unfortunately it's not a priority for me at the moment. If you're a risk-accepting person, I'm like 90% sure the live GitHub version is fine but I can't say for sure since I haven't tested it myself.

**Comment by Webatron11** [comment]
Ill give it a shot sooner or later and see if its good. Might put together a build guide too. Kits would be s splendid idea, especially for the any acrylic pieces

**Comment by thatfellarobin** [comment]
Yeah. What I really need is to talk to someone who has experience putting together and selling kits, and to learn from them. I have no experience doing something like that so I feel like I would make a ton of mistakes if I tried on my own.

**Comment by thatfellarobin** [comment]
Thanks for your interest btw! It really brightens my day to hear about people who still take an interest in this project.

**Comment by Webatron11** [comment]
I think a friend mentioned it ages ago and I am hunting down a nice setup for travel/school and enjoyed the aesthetics youve put together. Is the second layer cumbersome to access often? Another keyboard nerd mentioned he wouldnt want to use the board due to it being 40%

**Comment by thatfellarobin** [comment]
40% is not for everyone. I think it's a matter of how much you are committed to learning new muscle memory. I myself am a 40% noob, and I don't use this keyboard as a daily driver. However, that's partly because I only have one set of keycaps and this keyboard isn't great for some things like gaming lol.

**Comment by Webatron11** [comment]
Im gonna put together a BOM and see how it costs in AUS. I will close this issue as it has gotten extremely off-topic.
